// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: internal/server/proto/structs.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Duty_Fork int32

const (
	Duty_Phase0    Duty_Fork = 0
	Duty_Altair    Duty_Fork = 1
	Duty_Bellatrix Duty_Fork = 2
)

// Enum value maps for Duty_Fork.
var (
	Duty_Fork_name = map[int32]string{
		0: "Phase0",
		1: "Altair",
		2: "Bellatrix",
	}
	Duty_Fork_value = map[string]int32{
		"Phase0":    0,
		"Altair":    1,
		"Bellatrix": 2,
	}
)

func (x Duty_Fork) Enum() *Duty_Fork {
	p := new(Duty_Fork)
	*p = x
	return p
}

func (x Duty_Fork) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Duty_Fork) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_server_proto_structs_proto_enumTypes[0].Descriptor()
}

func (Duty_Fork) Type() protoreflect.EnumType {
	return &file_internal_server_proto_structs_proto_enumTypes[0]
}

func (x Duty_Fork) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Duty_Fork.Descriptor instead.
func (Duty_Fork) EnumDescriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 0}
}

type Duty_State int32

const (
	Duty_UNKNOWN  Duty_State = 0
	Duty_PENDING  Duty_State = 1
	Duty_COMPLETE Duty_State = 2
	Duty_FAILED   Duty_State = 3
	Duty_CANCELED Duty_State = 4
)

// Enum value maps for Duty_State.
var (
	Duty_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "COMPLETE",
		3: "FAILED",
		4: "CANCELED",
	}
	Duty_State_value = map[string]int32{
		"UNKNOWN":  0,
		"PENDING":  1,
		"COMPLETE": 2,
		"FAILED":   3,
		"CANCELED": 4,
	}
)

func (x Duty_State) Enum() *Duty_State {
	p := new(Duty_State)
	*p = x
	return p
}

func (x Duty_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Duty_State) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_server_proto_structs_proto_enumTypes[1].Descriptor()
}

func (Duty_State) Type() protoreflect.EnumType {
	return &file_internal_server_proto_structs_proto_enumTypes[1]
}

func (x Duty_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Duty_State.Descriptor instead.
func (Duty_State) EnumDescriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 1}
}

type Genesis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
}

func (x *Genesis) Reset() {
	*x = Genesis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genesis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genesis) ProtoMessage() {}

func (x *Genesis) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genesis.ProtoReflect.Descriptor instead.
func (*Genesis) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{0}
}

func (x *Genesis) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

type ValidatorListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ValidatorListRequest) Reset() {
	*x = ValidatorListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorListRequest) ProtoMessage() {}

func (x *ValidatorListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorListRequest.ProtoReflect.Descriptor instead.
func (*ValidatorListRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{1}
}

type ValidatorListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Validators []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (x *ValidatorListResponse) Reset() {
	*x = ValidatorListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorListResponse) ProtoMessage() {}

func (x *ValidatorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorListResponse.ProtoReflect.Descriptor instead.
func (*ValidatorListResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorListResponse) GetValidators() []*Validator {
	if x != nil {
		return x.Validators
	}
	return nil
}

type ListDutiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidatorId int64 `protobuf:"varint,1,opt,name=validatorId,proto3" json:"validatorId,omitempty"`
}

func (x *ListDutiesRequest) Reset() {
	*x = ListDutiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDutiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDutiesRequest) ProtoMessage() {}

func (x *ListDutiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDutiesRequest.ProtoReflect.Descriptor instead.
func (*ListDutiesRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{3}
}

func (x *ListDutiesRequest) GetValidatorId() int64 {
	if x != nil {
		return x.ValidatorId
	}
	return 0
}

type ListDutiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duties []*Duty `protobuf:"bytes,1,rep,name=duties,proto3" json:"duties,omitempty"`
}

func (x *ListDutiesResponse) Reset() {
	*x = ListDutiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDutiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDutiesResponse) ProtoMessage() {}

func (x *ListDutiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDutiesResponse.ProtoReflect.Descriptor instead.
func (*ListDutiesResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{4}
}

func (x *ListDutiesResponse) GetDuties() []*Duty {
	if x != nil {
		return x.Duties
	}
	return nil
}

type Duty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the identifier of the duty
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// pubKey is the public key of the validator that signs the job
	PubKey string `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	// slot is the slot at which this job was created
	Slot uint64 `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	// active_time is the time when this duty is meant to be executed
	ActiveTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=active_time,json=activeTime,proto3" json:"active_time,omitempty"`
	// blockedBy is the list of duties for which this duty is blocked
	BlockedBy      []string `protobuf:"bytes,5,rep,name=blockedBy,proto3" json:"blockedBy,omitempty"`
	Epoch          uint64   `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ValidatorIndex uint64   `protobuf:"varint,8,opt,name=validatorIndex,proto3" json:"validatorIndex,omitempty"`
	// Types that are assignable to Job:
	//	*Duty_BlockProposal_
	//	*Duty_Attestation_
	//	*Duty_AttestationAggregate_
	//	*Duty_SyncCommittee_
	//	*Duty_SyncCommitteeAggregate_
	Job    isDuty_Job   `protobuf_oneof:"job"`
	Result *Duty_Result `protobuf:"bytes,30,opt,name=result,proto3" json:"result,omitempty"`
	State  Duty_State   `protobuf:"varint,31,opt,name=state,proto3,enum=proto.Duty_State" json:"state,omitempty"`
	Fork   Duty_Fork    `protobuf:"varint,32,opt,name=fork,proto3,enum=proto.Duty_Fork" json:"fork,omitempty"`
}

func (x *Duty) Reset() {
	*x = Duty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty) ProtoMessage() {}

func (x *Duty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty.ProtoReflect.Descriptor instead.
func (*Duty) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5}
}

func (x *Duty) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Duty) GetPubKey() string {
	if x != nil {
		return x.PubKey
	}
	return ""
}

func (x *Duty) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Duty) GetActiveTime() *timestamp.Timestamp {
	if x != nil {
		return x.ActiveTime
	}
	return nil
}

func (x *Duty) GetBlockedBy() []string {
	if x != nil {
		return x.BlockedBy
	}
	return nil
}

func (x *Duty) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Duty) GetValidatorIndex() uint64 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (m *Duty) GetJob() isDuty_Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (x *Duty) GetBlockProposal() *Duty_BlockProposal {
	if x, ok := x.GetJob().(*Duty_BlockProposal_); ok {
		return x.BlockProposal
	}
	return nil
}

func (x *Duty) GetAttestation() *Duty_Attestation {
	if x, ok := x.GetJob().(*Duty_Attestation_); ok {
		return x.Attestation
	}
	return nil
}

func (x *Duty) GetAttestationAggregate() *Duty_AttestationAggregate {
	if x, ok := x.GetJob().(*Duty_AttestationAggregate_); ok {
		return x.AttestationAggregate
	}
	return nil
}

func (x *Duty) GetSyncCommittee() *Duty_SyncCommittee {
	if x, ok := x.GetJob().(*Duty_SyncCommittee_); ok {
		return x.SyncCommittee
	}
	return nil
}

func (x *Duty) GetSyncCommitteeAggregate() *Duty_SyncCommitteeAggregate {
	if x, ok := x.GetJob().(*Duty_SyncCommitteeAggregate_); ok {
		return x.SyncCommitteeAggregate
	}
	return nil
}

func (x *Duty) GetResult() *Duty_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Duty) GetState() Duty_State {
	if x != nil {
		return x.State
	}
	return Duty_UNKNOWN
}

func (x *Duty) GetFork() Duty_Fork {
	if x != nil {
		return x.Fork
	}
	return Duty_Phase0
}

type isDuty_Job interface {
	isDuty_Job()
}

type Duty_BlockProposal_ struct {
	BlockProposal *Duty_BlockProposal `protobuf:"bytes,20,opt,name=blockProposal,proto3,oneof"`
}

type Duty_Attestation_ struct {
	Attestation *Duty_Attestation `protobuf:"bytes,21,opt,name=attestation,proto3,oneof"`
}

type Duty_AttestationAggregate_ struct {
	AttestationAggregate *Duty_AttestationAggregate `protobuf:"bytes,22,opt,name=attestationAggregate,proto3,oneof"`
}

type Duty_SyncCommittee_ struct {
	SyncCommittee *Duty_SyncCommittee `protobuf:"bytes,23,opt,name=syncCommittee,proto3,oneof"`
}

type Duty_SyncCommitteeAggregate_ struct {
	SyncCommitteeAggregate *Duty_SyncCommitteeAggregate `protobuf:"bytes,24,opt,name=syncCommitteeAggregate,proto3,oneof"`
}

func (*Duty_BlockProposal_) isDuty_Job() {}

func (*Duty_Attestation_) isDuty_Job() {}

func (*Duty_AttestationAggregate_) isDuty_Job() {}

func (*Duty_SyncCommittee_) isDuty_Job() {}

func (*Duty_SyncCommitteeAggregate_) isDuty_Job() {}

type Validator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index           uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	PubKey          string `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	ActivationEpoch uint64 `protobuf:"varint,3,opt,name=activationEpoch,proto3" json:"activationEpoch,omitempty"`
	PrivKey         string `protobuf:"bytes,4,opt,name=privKey,proto3" json:"privKey,omitempty"` // provisional
}

func (x *Validator) Reset() {
	*x = Validator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{6}
}

func (x *Validator) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Validator) GetPubKey() string {
	if x != nil {
		return x.PubKey
	}
	return ""
}

func (x *Validator) GetActivationEpoch() uint64 {
	if x != nil {
		return x.ActivationEpoch
	}
	return 0
}

func (x *Validator) GetPrivKey() string {
	if x != nil {
		return x.PrivKey
	}
	return ""
}

type Duty_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockProposal          *Duty_BlockProposalResult          `protobuf:"bytes,50,opt,name=blockProposal,proto3" json:"blockProposal,omitempty"`
	Attestation            *Duty_AttestationResult            `protobuf:"bytes,51,opt,name=Attestation,proto3" json:"Attestation,omitempty"`
	AttestationAggregate   *Duty_AttestationAggregateResult   `protobuf:"bytes,52,opt,name=AttestationAggregate,proto3" json:"AttestationAggregate,omitempty"`
	SyncCommittee          *Duty_SyncCommitteeResult          `protobuf:"bytes,53,opt,name=SyncCommittee,proto3" json:"SyncCommittee,omitempty"`
	SyncCommitteeAggregate *Duty_SyncCommitteeAggregateResult `protobuf:"bytes,54,opt,name=SyncCommitteeAggregate,proto3" json:"SyncCommitteeAggregate,omitempty"`
}

func (x *Duty_Result) Reset() {
	*x = Duty_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_Result) ProtoMessage() {}

func (x *Duty_Result) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_Result.ProtoReflect.Descriptor instead.
func (*Duty_Result) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Duty_Result) GetBlockProposal() *Duty_BlockProposalResult {
	if x != nil {
		return x.BlockProposal
	}
	return nil
}

func (x *Duty_Result) GetAttestation() *Duty_AttestationResult {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *Duty_Result) GetAttestationAggregate() *Duty_AttestationAggregateResult {
	if x != nil {
		return x.AttestationAggregate
	}
	return nil
}

func (x *Duty_Result) GetSyncCommittee() *Duty_SyncCommitteeResult {
	if x != nil {
		return x.SyncCommittee
	}
	return nil
}

func (x *Duty_Result) GetSyncCommitteeAggregate() *Duty_SyncCommitteeAggregateResult {
	if x != nil {
		return x.SyncCommitteeAggregate
	}
	return nil
}

type Duty_BlockProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Duty_BlockProposal) Reset() {
	*x = Duty_BlockProposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_BlockProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_BlockProposal) ProtoMessage() {}

func (x *Duty_BlockProposal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_BlockProposal.ProtoReflect.Descriptor instead.
func (*Duty_BlockProposal) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 1}
}

type Duty_BlockProposalResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root      []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Duty_BlockProposalResult) Reset() {
	*x = Duty_BlockProposalResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_BlockProposalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_BlockProposalResult) ProtoMessage() {}

func (x *Duty_BlockProposalResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_BlockProposalResult.ProtoReflect.Descriptor instead.
func (*Duty_BlockProposalResult) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 2}
}

func (x *Duty_BlockProposalResult) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Duty_BlockProposalResult) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Duty_Attestation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitteeIndex   uint64 `protobuf:"varint,1,opt,name=committeeIndex,proto3" json:"committeeIndex,omitempty"`
	CommitteeLength  uint64 `protobuf:"varint,2,opt,name=committeeLength,proto3" json:"committeeLength,omitempty"`
	CommitteesAtSlot uint64 `protobuf:"varint,3,opt,name=committeesAtSlot,proto3" json:"committeesAtSlot,omitempty"`
}

func (x *Duty_Attestation) Reset() {
	*x = Duty_Attestation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_Attestation) ProtoMessage() {}

func (x *Duty_Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_Attestation.ProtoReflect.Descriptor instead.
func (*Duty_Attestation) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 3}
}

func (x *Duty_Attestation) GetCommitteeIndex() uint64 {
	if x != nil {
		return x.CommitteeIndex
	}
	return 0
}

func (x *Duty_Attestation) GetCommitteeLength() uint64 {
	if x != nil {
		return x.CommitteeLength
	}
	return 0
}

func (x *Duty_Attestation) GetCommitteesAtSlot() uint64 {
	if x != nil {
		return x.CommitteesAtSlot
	}
	return 0
}

type Duty_AttestationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root   []byte                             `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Source *Duty_AttestationResult_Checkpoint `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Target *Duty_AttestationResult_Checkpoint `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *Duty_AttestationResult) Reset() {
	*x = Duty_AttestationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_AttestationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_AttestationResult) ProtoMessage() {}

func (x *Duty_AttestationResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_AttestationResult.ProtoReflect.Descriptor instead.
func (*Duty_AttestationResult) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 4}
}

func (x *Duty_AttestationResult) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Duty_AttestationResult) GetSource() *Duty_AttestationResult_Checkpoint {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Duty_AttestationResult) GetTarget() *Duty_AttestationResult_Checkpoint {
	if x != nil {
		return x.Target
	}
	return nil
}

type Duty_AttestationAggregate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelectionProof []byte `protobuf:"bytes,1,opt,name=selectionProof,proto3" json:"selectionProof,omitempty"`
}

func (x *Duty_AttestationAggregate) Reset() {
	*x = Duty_AttestationAggregate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_AttestationAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_AttestationAggregate) ProtoMessage() {}

func (x *Duty_AttestationAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_AttestationAggregate.ProtoReflect.Descriptor instead.
func (*Duty_AttestationAggregate) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 5}
}

func (x *Duty_AttestationAggregate) GetSelectionProof() []byte {
	if x != nil {
		return x.SelectionProof
	}
	return nil
}

type Duty_AttestationAggregateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Duty_AttestationAggregateResult) Reset() {
	*x = Duty_AttestationAggregateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_AttestationAggregateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_AttestationAggregateResult) ProtoMessage() {}

func (x *Duty_AttestationAggregateResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_AttestationAggregateResult.ProtoReflect.Descriptor instead.
func (*Duty_AttestationAggregateResult) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 6}
}

type Duty_SyncCommittee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Duty_SyncCommittee) Reset() {
	*x = Duty_SyncCommittee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_SyncCommittee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_SyncCommittee) ProtoMessage() {}

func (x *Duty_SyncCommittee) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_SyncCommittee.ProtoReflect.Descriptor instead.
func (*Duty_SyncCommittee) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 7}
}

type Duty_SyncCommitteeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Duty_SyncCommitteeResult) Reset() {
	*x = Duty_SyncCommitteeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_SyncCommitteeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_SyncCommitteeResult) ProtoMessage() {}

func (x *Duty_SyncCommitteeResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_SyncCommitteeResult.ProtoReflect.Descriptor instead.
func (*Duty_SyncCommitteeResult) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 8}
}

type Duty_SyncCommitteeAggregate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelectionProof    []byte `protobuf:"bytes,1,opt,name=selectionProof,proto3" json:"selectionProof,omitempty"`
	SubCommitteeIndex uint64 `protobuf:"varint,2,opt,name=subCommitteeIndex,proto3" json:"subCommitteeIndex,omitempty"`
}

func (x *Duty_SyncCommitteeAggregate) Reset() {
	*x = Duty_SyncCommitteeAggregate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_SyncCommitteeAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_SyncCommitteeAggregate) ProtoMessage() {}

func (x *Duty_SyncCommitteeAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_SyncCommitteeAggregate.ProtoReflect.Descriptor instead.
func (*Duty_SyncCommitteeAggregate) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 9}
}

func (x *Duty_SyncCommitteeAggregate) GetSelectionProof() []byte {
	if x != nil {
		return x.SelectionProof
	}
	return nil
}

func (x *Duty_SyncCommitteeAggregate) GetSubCommitteeIndex() uint64 {
	if x != nil {
		return x.SubCommitteeIndex
	}
	return 0
}

type Duty_SyncCommitteeAggregateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Duty_SyncCommitteeAggregateResult) Reset() {
	*x = Duty_SyncCommitteeAggregateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_SyncCommitteeAggregateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_SyncCommitteeAggregateResult) ProtoMessage() {}

func (x *Duty_SyncCommitteeAggregateResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_SyncCommitteeAggregateResult.ProtoReflect.Descriptor instead.
func (*Duty_SyncCommitteeAggregateResult) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 10}
}

type Duty_AttestationResult_Checkpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root  []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Epoch uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (x *Duty_AttestationResult_Checkpoint) Reset() {
	*x = Duty_AttestationResult_Checkpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_proto_structs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Duty_AttestationResult_Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duty_AttestationResult_Checkpoint) ProtoMessage() {}

func (x *Duty_AttestationResult_Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_structs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duty_AttestationResult_Checkpoint.ProtoReflect.Descriptor instead.
func (*Duty_AttestationResult_Checkpoint) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_structs_proto_rawDescGZIP(), []int{5, 4, 0}
}

func (x *Duty_AttestationResult_Checkpoint) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Duty_AttestationResult_Checkpoint) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_internal_server_proto_structs_proto protoreflect.FileDescriptor

var file_internal_server_proto_structs_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x47, 0x65,
	0x6e, 0x65, 0x73, 0x69, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x49, 0x0a, 0x15, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x35, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x64, 0x75, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x75, 0x74, 0x79, 0x52, 0x06, 0x64, 0x75, 0x74, 0x69, 0x65, 0x73, 0x22, 0xcc,
	0x0f, 0x0a, 0x04, 0x44, 0x75, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73,
	0x6c, 0x6f, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x42, 0x79, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x42, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x65,
	0x70, 0x6f, 0x63, 0x68, 0x12, 0x26, 0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x41, 0x0a, 0x0d,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x75, 0x74, 0x79,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x48, 0x00,
	0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12,
	0x3b, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x75, 0x74,
	0x79, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x0b, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x56, 0x0a, 0x14,
	0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x75, 0x74, 0x79, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x14,
	0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x65, 0x18, 0x17, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x75, 0x74, 0x79, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x12, 0x5c, 0x0a, 0x16, 0x73, 0x79, 0x6e, 0x63, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x75, 0x74, 0x79, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x65, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x16, 0x73,
	0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x41, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x75,
	0x74, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x75, 0x74, 0x79, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x6f,
	0x72, 0x6b, 0x18, 0x20, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x75, 0x74, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x6b, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6b,
	0x1a, 0x95, 0x03, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x45, 0x0a, 0x0d, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x18, 0x32, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x75, 0x74, 0x79, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x12, 0x3f, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x33, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x75, 0x74, 0x79, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x5a, 0x0a, 0x14, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x18, 0x34, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x75, 0x74, 0x79, 0x2e, 0x41,
	0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x14, 0x41, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12,
	0x45, 0x0a, 0x0d, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65,
	0x18, 0x35, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x75, 0x74, 0x79, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0d, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x12, 0x60, 0x0a, 0x16, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x18, 0x36, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x75, 0x74, 0x79, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x65, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x16, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x41,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x1a, 0x0f, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x1a, 0x47, 0x0a, 0x13, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x72, 0x6f, 0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x1a, 0x8b, 0x01, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x65, 0x73, 0x41, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x73, 0x41, 0x74, 0x53, 0x6c, 0x6f, 0x74,
	0x1a, 0xe3, 0x01, 0x0a, 0x11, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12, 0x40, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x75, 0x74, 0x79, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x75, 0x74, 0x79, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x1a, 0x36,
	0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x1a, 0x3e, 0x0a, 0x14, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x1a, 0x1c, 0x0a, 0x1a, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x1a, 0x0f, 0x0a, 0x0d, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x65, 0x1a, 0x15, 0x0a, 0x13, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x6e, 0x0a, 0x16,
	0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x41, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x2c,
	0x0a, 0x11, 0x73, 0x75, 0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x73, 0x75, 0x62, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x1e, 0x0a, 0x1c,
	0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x41, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2d, 0x0a, 0x04,
	0x46, 0x6f, 0x72, 0x6b, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x68, 0x61, 0x73, 0x65, 0x30, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x6c, 0x74, 0x61, 0x69, 0x72, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x42, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x72, 0x69, 0x78, 0x10, 0x02, 0x22, 0x49, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e, 0x43,
	0x45, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x42, 0x05, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x22, 0x7d, 0x0a,
	0x09, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x70, 0x6f,
	0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x32, 0xd7, 0x01, 0x0a,
	0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x74, 0x69, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x44, 0x75, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x42, 0x18, 0x5a, 0x16, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_server_proto_structs_proto_rawDescOnce sync.Once
	file_internal_server_proto_structs_proto_rawDescData = file_internal_server_proto_structs_proto_rawDesc
)

func file_internal_server_proto_structs_proto_rawDescGZIP() []byte {
	file_internal_server_proto_structs_proto_rawDescOnce.Do(func() {
		file_internal_server_proto_structs_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_server_proto_structs_proto_rawDescData)
	})
	return file_internal_server_proto_structs_proto_rawDescData
}

var file_internal_server_proto_structs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_server_proto_structs_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_server_proto_structs_proto_goTypes = []interface{}{
	(Duty_Fork)(0),                            // 0: proto.Duty.Fork
	(Duty_State)(0),                           // 1: proto.Duty.State
	(*Genesis)(nil),                           // 2: proto.Genesis
	(*ValidatorListRequest)(nil),              // 3: proto.ValidatorListRequest
	(*ValidatorListResponse)(nil),             // 4: proto.ValidatorListResponse
	(*ListDutiesRequest)(nil),                 // 5: proto.ListDutiesRequest
	(*ListDutiesResponse)(nil),                // 6: proto.ListDutiesResponse
	(*Duty)(nil),                              // 7: proto.Duty
	(*Validator)(nil),                         // 8: proto.Validator
	(*Duty_Result)(nil),                       // 9: proto.Duty.Result
	(*Duty_BlockProposal)(nil),                // 10: proto.Duty.BlockProposal
	(*Duty_BlockProposalResult)(nil),          // 11: proto.Duty.BlockProposalResult
	(*Duty_Attestation)(nil),                  // 12: proto.Duty.Attestation
	(*Duty_AttestationResult)(nil),            // 13: proto.Duty.AttestationResult
	(*Duty_AttestationAggregate)(nil),         // 14: proto.Duty.AttestationAggregate
	(*Duty_AttestationAggregateResult)(nil),   // 15: proto.Duty.AttestationAggregateResult
	(*Duty_SyncCommittee)(nil),                // 16: proto.Duty.SyncCommittee
	(*Duty_SyncCommitteeResult)(nil),          // 17: proto.Duty.SyncCommitteeResult
	(*Duty_SyncCommitteeAggregate)(nil),       // 18: proto.Duty.SyncCommitteeAggregate
	(*Duty_SyncCommitteeAggregateResult)(nil), // 19: proto.Duty.SyncCommitteeAggregateResult
	(*Duty_AttestationResult_Checkpoint)(nil), // 20: proto.Duty.AttestationResult.Checkpoint
	(*timestamp.Timestamp)(nil),               // 21: google.protobuf.Timestamp
	(*empty.Empty)(nil),                       // 22: google.protobuf.Empty
}
var file_internal_server_proto_structs_proto_depIdxs = []int32{
	8,  // 0: proto.ValidatorListResponse.validators:type_name -> proto.Validator
	7,  // 1: proto.ListDutiesResponse.duties:type_name -> proto.Duty
	21, // 2: proto.Duty.active_time:type_name -> google.protobuf.Timestamp
	10, // 3: proto.Duty.blockProposal:type_name -> proto.Duty.BlockProposal
	12, // 4: proto.Duty.attestation:type_name -> proto.Duty.Attestation
	14, // 5: proto.Duty.attestationAggregate:type_name -> proto.Duty.AttestationAggregate
	16, // 6: proto.Duty.syncCommittee:type_name -> proto.Duty.SyncCommittee
	18, // 7: proto.Duty.syncCommitteeAggregate:type_name -> proto.Duty.SyncCommitteeAggregate
	9,  // 8: proto.Duty.result:type_name -> proto.Duty.Result
	1,  // 9: proto.Duty.state:type_name -> proto.Duty.State
	0,  // 10: proto.Duty.fork:type_name -> proto.Duty.Fork
	11, // 11: proto.Duty.Result.blockProposal:type_name -> proto.Duty.BlockProposalResult
	13, // 12: proto.Duty.Result.Attestation:type_name -> proto.Duty.AttestationResult
	15, // 13: proto.Duty.Result.AttestationAggregate:type_name -> proto.Duty.AttestationAggregateResult
	17, // 14: proto.Duty.Result.SyncCommittee:type_name -> proto.Duty.SyncCommitteeResult
	19, // 15: proto.Duty.Result.SyncCommitteeAggregate:type_name -> proto.Duty.SyncCommitteeAggregateResult
	20, // 16: proto.Duty.AttestationResult.source:type_name -> proto.Duty.AttestationResult.Checkpoint
	20, // 17: proto.Duty.AttestationResult.target:type_name -> proto.Duty.AttestationResult.Checkpoint
	3,  // 18: proto.ValidatorService.ValidatorList:input_type -> proto.ValidatorListRequest
	5,  // 19: proto.ValidatorService.ListDuties:input_type -> proto.ListDutiesRequest
	22, // 20: proto.ValidatorService.GetGenesis:input_type -> google.protobuf.Empty
	4,  // 21: proto.ValidatorService.ValidatorList:output_type -> proto.ValidatorListResponse
	6,  // 22: proto.ValidatorService.ListDuties:output_type -> proto.ListDutiesResponse
	2,  // 23: proto.ValidatorService.GetGenesis:output_type -> proto.Genesis
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_internal_server_proto_structs_proto_init() }
func file_internal_server_proto_structs_proto_init() {
	if File_internal_server_proto_structs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_server_proto_structs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Genesis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDutiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDutiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_BlockProposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_BlockProposalResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_Attestation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_AttestationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_AttestationAggregate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_AttestationAggregateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_SyncCommittee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_SyncCommitteeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_SyncCommitteeAggregate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_SyncCommitteeAggregateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_proto_structs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Duty_AttestationResult_Checkpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_server_proto_structs_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Duty_BlockProposal_)(nil),
		(*Duty_Attestation_)(nil),
		(*Duty_AttestationAggregate_)(nil),
		(*Duty_SyncCommittee_)(nil),
		(*Duty_SyncCommitteeAggregate_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_server_proto_structs_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_proto_structs_proto_goTypes,
		DependencyIndexes: file_internal_server_proto_structs_proto_depIdxs,
		EnumInfos:         file_internal_server_proto_structs_proto_enumTypes,
		MessageInfos:      file_internal_server_proto_structs_proto_msgTypes,
	}.Build()
	File_internal_server_proto_structs_proto = out.File
	file_internal_server_proto_structs_proto_rawDesc = nil
	file_internal_server_proto_structs_proto_goTypes = nil
	file_internal_server_proto_structs_proto_depIdxs = nil
}
