// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: internal/testutil/proto/service.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DeployNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeployNodeRequest) Reset() {
	*x = DeployNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_testutil_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployNodeRequest) ProtoMessage() {}

func (x *DeployNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testutil_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployNodeRequest.ProtoReflect.Descriptor instead.
func (*DeployNodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_testutil_proto_service_proto_rawDescGZIP(), []int{0}
}

type DeployNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeployNodeResponse) Reset() {
	*x = DeployNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_testutil_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployNodeResponse) ProtoMessage() {}

func (x *DeployNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testutil_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployNodeResponse.ProtoReflect.Descriptor instead.
func (*DeployNodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_testutil_proto_service_proto_rawDescGZIP(), []int{1}
}

type DeployValidatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeployValidatorRequest) Reset() {
	*x = DeployValidatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_testutil_proto_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployValidatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployValidatorRequest) ProtoMessage() {}

func (x *DeployValidatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testutil_proto_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployValidatorRequest.ProtoReflect.Descriptor instead.
func (*DeployValidatorRequest) Descriptor() ([]byte, []int) {
	return file_internal_testutil_proto_service_proto_rawDescGZIP(), []int{2}
}

type DeployValidatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeployValidatorResponse) Reset() {
	*x = DeployValidatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_testutil_proto_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployValidatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployValidatorResponse) ProtoMessage() {}

func (x *DeployValidatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testutil_proto_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployValidatorResponse.ProtoReflect.Descriptor instead.
func (*DeployValidatorResponse) Descriptor() ([]byte, []int) {
	return file_internal_testutil_proto_service_proto_rawDescGZIP(), []int{3}
}

var File_internal_testutil_proto_service_proto protoreflect.FileDescriptor

var file_internal_testutil_proto_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x75,
	0x74, 0x69, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13,
	0x0a, 0x11, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa1,
	0x01, 0x0a, 0x0a, 0x45, 0x32, 0x45, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a,
	0x0a, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_testutil_proto_service_proto_rawDescOnce sync.Once
	file_internal_testutil_proto_service_proto_rawDescData = file_internal_testutil_proto_service_proto_rawDesc
)

func file_internal_testutil_proto_service_proto_rawDescGZIP() []byte {
	file_internal_testutil_proto_service_proto_rawDescOnce.Do(func() {
		file_internal_testutil_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_testutil_proto_service_proto_rawDescData)
	})
	return file_internal_testutil_proto_service_proto_rawDescData
}

var file_internal_testutil_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_testutil_proto_service_proto_goTypes = []interface{}{
	(*DeployNodeRequest)(nil),       // 0: proto.DeployNodeRequest
	(*DeployNodeResponse)(nil),      // 1: proto.DeployNodeResponse
	(*DeployValidatorRequest)(nil),  // 2: proto.DeployValidatorRequest
	(*DeployValidatorResponse)(nil), // 3: proto.DeployValidatorResponse
}
var file_internal_testutil_proto_service_proto_depIdxs = []int32{
	0, // 0: proto.E2EService.DeployNode:input_type -> proto.DeployNodeRequest
	2, // 1: proto.E2EService.DeployValidator:input_type -> proto.DeployValidatorRequest
	1, // 2: proto.E2EService.DeployNode:output_type -> proto.DeployNodeResponse
	3, // 3: proto.E2EService.DeployValidator:output_type -> proto.DeployValidatorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_testutil_proto_service_proto_init() }
func file_internal_testutil_proto_service_proto_init() {
	if File_internal_testutil_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_testutil_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_testutil_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_testutil_proto_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployValidatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_testutil_proto_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployValidatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_testutil_proto_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_testutil_proto_service_proto_goTypes,
		DependencyIndexes: file_internal_testutil_proto_service_proto_depIdxs,
		MessageInfos:      file_internal_testutil_proto_service_proto_msgTypes,
	}.Build()
	File_internal_testutil_proto_service_proto = out.File
	file_internal_testutil_proto_service_proto_rawDesc = nil
	file_internal_testutil_proto_service_proto_goTypes = nil
	file_internal_testutil_proto_service_proto_depIdxs = nil
}
